version: "3.9"

services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    volumes:
      - ${DATA_DIR}/db:/data/postgres
    ports:
      - "${DB_HOST_PORT}:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWD}
      PGDATA: /data/postgres
  app:
    build: .
    restart: always
    volumes:
      - ${DATA_DIR}/config:/config:ro
      - ${DATA_DIR}/git:/data/git
      - ${DATA_DIR}/rec:/data/rec
      - ${STORAGE_DIR}:/storage
  apiserver:
    build: .
    restart: always
    command: 
      - /app/apiserver
      - -config
      - /config/config.json
    ports:
      - "${APISERVER_HOST_PORT}:8080"
    volumes:
      - ${DATA_DIR}/config:/config:ro
  web:
    container_name: pgweb
    restart: always
    image: sosedoff/pgweb
    ports:
      - "${WEB_HOST_PORT}:8081"
    entrypoint:
      - "/usr/bin/pgweb"
      - "--bind=0.0.0.0"
      - "--listen=8081"
      - "--readonly"
      - "--host=db"
      - "--port=5432"
      - "--user=postgres"
      - "--pass=${DB_PASSWD}"
      - "--db=criticality_score"
      - "--ssl=disable"
